server:
  port: 8080

spring:
  application:
      name: urlshortner
  data:
    mongodb:
      uri: mongodb://localhost:27018/urlshortener

  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

# Optional: if you're using devtools
spring.devtools.restart.enabled: true
